version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: bookstorage-db
    restart: always
    environment:
      POSTGRES_DB: bookstorage
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"

  book-storage:
    build: .
    container_name: book-storage-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstorage
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: 123
